# Generated by Django 4.2.8 on 2023-12-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Trip_start_date', models.DateField(null=True)),
                ('Trip_end_date', models.DateField(null=True)),
                ('Your_State', models.CharField(max_length=50)),
                ('Your_District', models.CharField(max_length=50)),
                ('Distination', models.CharField(max_length=50)),
                ('Members_in_Trip', models.IntegerField()),
                ('Adults_in_Trip', models.IntegerField()),
                ('Childerns_in_Trip', models.IntegerField()),
            ],
        ),
    ]
